// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMewGLSqrlbUYUoNorzUXhx9RWIaxrAH8',
    appId: '1:519379931437:web:6c541ab61631982c95c3a4',
    messagingSenderId: '519379931437',
    projectId: 'drive-app-ec08e',
    authDomain: 'drive-app-ec08e.firebaseapp.com',
    storageBucket: 'drive-app-ec08e.firebasestorage.app',
    measurementId: 'G-MR34YTXY3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs1wcdBHQ6y2oU4o9c3uNxwLqPeMGndi0',
    appId: '1:519379931437:android:4af7f5f9968e361b95c3a4',
    messagingSenderId: '519379931437',
    projectId: 'drive-app-ec08e',
    storageBucket: 'drive-app-ec08e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5sH6kn6CGHraZZgfFVNyjyJUR-g0cMgY',
    appId: '1:519379931437:ios:86ef0bda49b62f8595c3a4',
    messagingSenderId: '519379931437',
    projectId: 'drive-app-ec08e',
    storageBucket: 'drive-app-ec08e.firebasestorage.app',
    iosBundleId: 'com.example.routex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5sH6kn6CGHraZZgfFVNyjyJUR-g0cMgY',
    appId: '1:519379931437:ios:86ef0bda49b62f8595c3a4',
    messagingSenderId: '519379931437',
    projectId: 'drive-app-ec08e',
    storageBucket: 'drive-app-ec08e.firebasestorage.app',
    iosBundleId: 'com.example.routex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMewGLSqrlbUYUoNorzUXhx9RWIaxrAH8',
    appId: '1:519379931437:web:4781c5f68aa2988495c3a4',
    messagingSenderId: '519379931437',
    projectId: 'drive-app-ec08e',
    authDomain: 'drive-app-ec08e.firebaseapp.com',
    storageBucket: 'drive-app-ec08e.firebasestorage.app',
    measurementId: 'G-YD0MR0NNRV',
  );
}
